---
redshift_config:
  dryrun: False  
  port: 5439
  username: <user_name>
  database_name: <db_name>
  cluster_id: <cluster_id>
  url: <url> 
  region: <region>
  bucket_name: <s3_bucket_name>
  parallel_threads: <Number of parallel threads e.g. 30> 
  conn_string: <connection string>
schemas:
- schema_name: <schema_name> 
  tables:
  - table_name: <table_name>
    sort_key_col: <sort_key_name>
- schema_name: <schema_name_2>
  tables:
  - table_name: <table_name_2>
  - table_name: <table_name_3>
